---
- hosts: localhost
  connection: local
  become: true
  tasks:

    - name: update all packages
      ansible.builtin.dnf:
        update: yes
        update_cache: yes
      when: ansible_distribution == "RedHat"
